# Generated by Django 5.2.6 on 2025-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Imagem ativa?'),
        ),
    ]
