# Generated by Django 5.2.6 on 2025-10-28 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0006_pedidoparticipacaocampanha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoparticipacaocampanha',
            name='data_fim',
        ),
        migrations.AddField(
            model_name='pedidoparticipacaocampanha',
            name='personagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personagem_usuario', to='area_administrativa.personagem'),
        ),
        migrations.AlterField(
            model_name='pedidoparticipacaocampanha',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Reprovada')], default='P', max_length=1),
        ),
    ]
