# Generated by Django 5.2.7 on 2025-10-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0007_remove_pedidoparticipacaocampanha_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='vida',
            field=models.PositiveIntegerField(default=10, verbose_name='vida'),
            preserve_default=False,
        ),
    ]
