# Generated by Django 5.2.7 on 2025-10-29 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0008_personagem_vida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='vida',
            field=models.PositiveIntegerField(default=10, verbose_name='vida'),
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='area_administrativa.campanha')),
            ],
            options={
                'verbose_name': 'Sessão de Jogo',
                'verbose_name_plural': 'Sessões de Jogo',
                'ordering': ('-data_inicio',),
            },
        ),
        migrations.CreateModel(
            name='CampanhaJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_atual', models.PositiveIntegerField(default=10)),
                ('experiencia', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expulso', 'Expulso'), ('morto', 'Morto')], default='ativo', max_length=20)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='area_administrativa.campanha')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='area_administrativa.personagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_participadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador da Campanha',
                'verbose_name_plural': 'Jogadores da Campanha',
                'ordering': ('campanha', 'personagem'),
                'unique_together': {('campanha', 'personagem')},
            },
        ),
    ]
