# Generated by Django 5.2.8 on 2025-11-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0009_alter_personagem_vida_jogo_campanhajogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='anotacoes',
            field=models.TextField(blank=True, null=True, verbose_name='anotações'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='publico',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
