# Generated by Django 5.2.8 on 2025-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0010_campanha_anotacoes_campanha_ativo_campanha_publico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_raca', models.CharField(blank=True, max_length=100, null=True, verbose_name='raca')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ('nome_raca',),
            },
        ),
        migrations.AlterField(
            model_name='campanha',
            name='anotacoes',
            field=models.JSONField(blank=True, null=True, verbose_name='anotações'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='descricao'),
        ),
    ]
