# Generated by Django 5.2.8 on 2025-11-13 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_administrativa', '0011_raca_alter_campanha_anotacoes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raca',
        ),
    ]
